---
namespace: community
name: vmware
# the version key is generated during the release by Zuul
# https://github.com/ansible-network/releases/tree/master/ansible_releases/cmd
# A script based on https://pypi.org/project/pbr/ will generate the version
# key. The version value depends on the tag or the last git tag.
readme: README.md
authors:
  - Ansible (https://github.com/ansible)
description:
license_file: LICENSE
tags:
  - cloud
  - vmware
  - virtualization
dependencies: {}
repository: https://github.com/ansible-collections/vmware.git
homepage: https://github.com/ansible-collections/vmware
issues: https://github.com/ansible-collections/vmware/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
