---
- name: release collection
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    collection_namespace: "community"
    collection_name: "vmware"
    collection_version: "{{ github_tag.split('/')[-1] | regex_search('(\\d.\\d.\\d.*)') }}"
    collection_repo: https://github.com/ansible-collections/community.vmware
    api_key: undef

  tasks:
    - name: rename official galaxy.yml
      command: mv {{ playbook_dir }}/galaxy.yml {{ playbook_dir }}/galaxy.official

    - name: create galaxy.yml
      template:
        src: "{{ playbook_dir}}/galaxy.yml.j2"
        dest: "{{ playbook_dir }}/galaxy.yml"

    - name: build collection
      command:
        cmd: ansible-galaxy collection build
        chdir: "{{ playbook_dir }}"
        creates: "{{ playbook_dir }}/{{ collection_namespace }}-{{ collection_name }}-{{ collection_version }}.tar.gz"
      tags: build

    - name: install collection
      command:
        cmd: "ansible-galaxy collection install {{ collection_namespace }}-{{ collection_name }}-{{ collection_version }}.tar.gz -p ~/.ansible/collections/"
        chdir: "{{ playbook_dir }}"
      tags: install

    - name: publish collection
      command:
        cmd: "ansible-galaxy collection publish --api-key={{ api_key }} {{ collection_namespace }}-{{ collection_name }}-{{ collection_version }}.tar.gz"
        chdir: "{{ playbook_dir }}"
      tags: publish

    - name: git cleanup
      command:
        cmd: git reset --hard
      tags: cleanup

    - name: remove galaxy.yml
      file:
        path: "{{ playbook_dir }}/galaxy.yml"
        state: absent

    - name: restore official galaxy.yml
      command: mv {{ playbook_dir }}/galaxy.official {{ playbook_dir }}/galaxy.yml