---
name: nox
'on':
  push:
    branches:
      - main
      - stable-*
  pull_request:

permissions:
  contents: read

jobs:
  nox:
    runs-on: ubuntu-latest
    name: "Run nox"
    steps:
      - name: Check out collection
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Run nox
        uses: ansible-community/antsibull-nox@efe6769cb9fa52e98fd6b3a4711dbd588e5512ce
